"use client"
import Link from 'next/link'
import './globals.css'
import { useEffect, useState } from 'react'

export const metadata = {
  title: 'Welcome!',
  description: 'Generated by woon',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [topics, setTopics] = useState([]);
  //console.log("topics:", topics);

  useEffect(()=>{
    fetch("http://localhost:3000/api/topics")
    .then(resp=>resp.json())
    .then(result=>{
      //console.log("resutl", result);
      setTopics(result);
    })
  }, []);

  // const tags = [];
  // for(let i = 0; i < topics.length; i++){
  //   // @ts-ignore
  //   tags.push(<li>{topics[i].title}</li>)
  // }
  // console.log("tags", tags);

  return (
    <html lang="en">
      
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <input type="text" placeholder="search"></input>
        <ol>
          {[
            topics.map(t=>{
              // @ts-ignore
              return <li key={t.id}><Link href={"/read/" + t.id}>{t.title}</Link> </li>
            })
          ]}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">create</Link>
          </li>
          <li>
            <Link href="/update/1">update</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  )
}
